### PR TITLE
Adds French GenericName and Comment

### PR DESCRIPTION
**Pull request by trebmuh**
for people with a French locale

### CODE REVIEW

**Comment by iurienistor** [comment]
Hi Olivier! Thank you :)

**Comment by trebmuh** [comment]
my pleasure, thanks for the quick merge

**Comment by iurienistor** [comment]
Here is issue in installing the MIME type icon for the presets file "*.gkick". If you can, you can try to solve this, I've done some in this direction on GNOME, but I don't see the icon for files with extension *.gkick after setup: https://gitlab.com/iurie/geonkick/issues/54

**Comment by trebmuh** [comment]
You might want to look at [how Qtractor handles that](https://github.com/rncbc/qtractor/tree/master/src/mimetypes) which is one software with which this is working here

**Comment by iurienistor** [comment]
Ok, thank you! When I'll return to this issue I'll see hat is happening.

**Pull request merged**
